### ISSUE TITLE
The PR template's pytest invocation trips conftest shadowing between the two suites

### ISSUE THREAD

**Issue by niko86** [niko86/laterite#828]
Found while running #821's gates; pre-existing, reproduced with that branch's changes removed.

## What happens

The PR template (and CLAUDE.md) say:

    uv run pytest tests/ packages/laterite/tests -q

Run that way — root suite first, serial — 45 tests fail, all in `tests/test_build_marker_faithful.py::test_the_ignore_hook_reads_the_same_marker[...]`, with:

    ImportError: cannot import name '_declares_marker' from 'conftest'
    (packages/laterite/tests/conftest.py)

The test does `from conftest import _declares_marker`, a bare module name that resolves to whichever `conftest.py` claimed that name in `sys.modules` — and in this arg order the wheel suite's conftest wins by the time the test executes.

CI is green because ci.yml runs the suites the other way around and under xdist (`pytest packages/laterite/tests tests -n 4`), where the root conftest holds the name. So the template's command and CI's command disagree, and the one contributors are told to run is the one that fails.

## Verified shapes

- `pytest tests/` alone — green
- `pytest packages/laterite/tests tests -n 4` (CI's shape) — green, 1944 passed
- `pytest tests/ packages/laterite/tests -q` (the template's shape) — 45 failed
- the failing test passes in isolation, and in small combinations — it needs both suites in one serial session, root first

## Possible fixes (whoever picks this up decides)

- import the helper by path in `test_build_marker_faithful.py` (`importlib.util.spec_from_file_location`, the way the tool-gate tests already load hyphenated tools), or
- align the template/CLAUDE.md command with CI's invocation, or
- both — the bare `from conftest import ...` stays order-fragile either way.
